### ISSUE TITLE
Face Detection Client Not Working

### ISSUE THREAD

**Issue by sriks6711** [gvinciguerra/countmein#3]
Am on Windows and when I execute the client, it is crashing after a face has been detected...

E:\countmein\clients>python camera_node.py
[[ 85 168 289 289]] // I printed faces() to debug
Traceback (most recent call last):
  File "E:\countmein\clients\camera_node.py", line 155, in <module>
    track_unknown_faces(faces, frame)
  File "E:\countmein\clients\camera_node.py", line 81, in track_unknown_faces
    new_tracker = cv2.Tracker_create("MEDIANFLOW")  # KCF MEDIANFLOW
AttributeError: module 'cv2.cv2' has no attribute 'Tracker_create'
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wvn_it83\opencv\modules\videoio\src\cap_msmf.cpp (434) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by gvinciguerra** [comment]
Sorry, I'm not maintaining this repo anymore. Anyway, be sure to use the OpenCV version indicated in the readme
